config/routes.rb
OutpatientThesis::Application.routes.draw do

  resources :orthodontics
  resources :pediatrics
  resources :schedules
  resources :users
  resources :inventories
  resources :analytics
  resources :immunizations 
  resources :pendings
  resources :ortho_examinations
  resources :pedia_examinations
  resources :sessions
  
  match 'orthodontics', to: 'orthodontics#create'
  match '/home', to: 'access#home'
  match '/print_ortho', to: 'orthodontics#print_records'
  match '/print_pedia', to: 'pediatrics#print_records'
  match '/logout', to: 'sessions#destroy', via: :delete

  # T`he priority is based upon order of creation:
  # first created -> highest priority.
  # root :to => "public#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#login'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
  
end

app/models/pediatric.rb
class Pediatric < ActiveRecord::Base
  
  	attr_accessible :id, :full_name, :address, :contact_no, :age, :birth_date, :sex, :mother_name, :father_name, :f_age, :m_age, :f_occupation, :m_occupation, :type_of_feeding, :supplementary, :name_of_vaccination, :vaccination, :booster, :type_of_vaccination, :term, :head, :delivery, :chest_circ, :food, :birth_weight, :abdominal, :medicine, :birth_length, :obsterician, :head_circ, :others, :weight, :height
    
    REGEX = /^([^\d\W]|[-\s])*$/

  	# "sexy" validations
  	validates :full_name, :presence => true, :format => { :with => REGEX }, :length => {:maximum => 50}, :uniqueness => true
  	validates :address, :presence => true, :length => {:maximum => 80}
  	validates :contact_no, :presence => true, :length => {:maximum => 15}

	def self.search(search, page)
    name = "full_name"	
		paginate :per_page => 10 , :page => page,
				 :conditions => [ "full_name || lower(full_name) LIKE ?", "%#{search}%" ],
				 :order => name
	end
  
 	#scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"])}

  def self.total_on(date)
    where("date(created_at) = ?", date).count(:full_name)
  end
end

app/controllers/pediatrics_controller.rb
class PediatricsController < ApplicationController

	layout 'admin', :except => [:print_records]

	before_filter :find_pediatric
	before_filter :confirm_logged_in
	# before_filter :confirm_admin, :except => [:index, :new, :create, :show]
	before_filter :find_schedules
	before_filter :find_pendings
	before_filter :load
	# before_filter :find_immune

	def load
		@pediatrics = Pediatric.search(params[:search], params[:page])
		@pediatric = Pediatric.new
		@immunizations = Immunization.where(:pediatric_id => params[:id])
	end

	def index
	end

	def show
		@pediatric = Pediatric.find(params[:id])
	end

	def print_records
		@pediatric = Pediatric.where(:pediatric_id => @pediatric.id)
		@pedia = Pediatric.find(params[:pediatric_id])
	end

	def create
		@pediatric = Pediatric.new(params[:pediatric])
		if @pediatric.save
			flash[:success] = "Successfully created record."	
			@pediatrics = Pediatric.search(params[:search], params[:page])
		end
	end

	def examination
		#show the examination content
		@examination = Pediatric.find(params[:id])
	end

	def create_examination
		@pediatric = Pediatric.find(params[:id])
		if @pediatric.update_attributes(params[:pedia])
			flash[:success] = "Successfully created record."
			@pediatrics = Pediatric.search(params[:search], params[:page])
		end
	end

	def edit
		@orthodontic = Orthodontic.find(params[:id])
		@pediatric = Pediatric.find(params[:id])
	end

	def update
		@pediatrics = Pediatric.find(params[:id])
		if @pediatrics.update_attributes(params[:pediatric])
			flash[:success] = "Successfully updated record."
			@pediatrics = Pediatric.search(params[:search], params[:page])
		end
	end

	def destroy
		@pediatric = Pediatric.find(params[:id]).destroy
		flash[:success] = "Pediatric patient destroyed."
		@pediatrics = Pediatric.search(params[:search], params[:page])
	end

	private

	def find_pediatric
	  if params[:id]
	    @pediatric = Pediatric.find_by_id(params[:id])
	  end
	end

end

app/helpers/pediatrics_helper.rb
module PediatricsHelper
end

app/views/pediatrics/_examination.html.haml
= form_for @pediatric, remote: true, :class => 'modal-form'  do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Pediatrics
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@pediatric)
  .addrecord
    %table
      %tr
        %td= f.label(:examination_date, "Examination Date")
        %td= f.date_select(:examination_date, :order => [:month, :day, :year])
      %tr
        %td= f.label(:weight)
        %td= f.text_field(:weight, :class=>'round half-size-input')
      %tr
        %td= f.label(:height)
        %td= f.text_field(:height, :class=>'round half-size-input')
      %tr
        %td= f.label(:history_physical_exams, "History and Physical Exams")
        %td= f.text_area(:history_physical_exams, :size => '40x5')
      %tr
        %td= f.label(:physicians_instructions, "Physician's Insructions")
        %td= f.text_area(:physicians_instructions, :size => '40x5')
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/pediatrics/_form.html.haml
= form_for @pediatric, remote: true, :class => 'modal-form'  do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Pediatrics
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@pediatric)
    .addrecord
      %table.pedia-addrecord
        %thead
          %tr
            %td{:colspan => "4"}
              %h4 Personal Information
        %tbody
          %tr
            %td= f.label(:full_name, "Full Name")
            %td{:colspan => "3"}= f.text_field(:full_name, :class=>'input-xlarge')
          %tr
            %td= f.label(:address, "Address")
            %td{:colspan => "3"}= f.text_field(:address, :class=>'input-xxlarge')
          %tr
            %td= f.label(:mother_name, "Mother's")
            %td{:colspan => "3"}
              = f.text_field(:mother_name, :class=>'input-medium', :placeholder => "Name")
              = f.text_field(:m_occupation, :class=>'input-medium', :placeholder => "Occupation")
              \&nbsp;
              %span> Age
              \&nbsp;
              \#{f.select(:m_age, 15..90, { :include_blank => true }, :class=>'auto')}
          %tr
            %td= f.label(:father_name, "Father's", :class=> 'left-margin')
            %td{:colspan => "3"}
              = f.text_field(:father_name, :class=>'input-medium', :placeholder => 'Name')
              = f.text_field(:f_occupation, :class=>'input-medium', :placeholder => "Occupation")
              \&nbsp;
              %span> Age
              \&nbsp;
              \#{f.select(:m_age, 15..90, { :include_blank => true }, :class=>'auto')}
          %tr
            %td= f.label(:birth_date, "Birth Date")
            %td{:colspan => "2"}
              = f.text_field(:birth_date, :class => 'input-medium datepicker', placeholder: 'YYYY-MM-DD')
              \&nbsp;
              %span> Age
              \&nbsp;
              \#{f.select(:age, 1..15, { :include_blank => true }, :class=>'round dropdown')}
          %tr
            %td= f.label(:contact_no)
            %td
              = f.text_field(:contact_no, :class=>'input-medium')
              \&nbsp;
              %span> Gender
              \&nbsp;
              \#{f.select(:sex, %w{Male Female})}

          / Birth History and Development
          %tr
            %th{:colspan => "5"}
              %h4 Birth History and Development
          %tr
            %td= f.label(:term)
            %td= f.text_field(:term, :class=>'input-large')
            %td= f.label(:head_circ)
            %td= f.text_field(:head_circ, :class=>'input-large')
          %tr
            %td= f.label(:delivery)
            %td= f.text_field(:delivery, :class=>'round input-large')
            %td= f.label(:chest_circ, "Chest Circ.")
            %td= f.text_field(:chest_circ, :class=>'input-large')
          %tr
            %td= f.label(:birth_weight, "Birth Weight")
            %td= f.text_field(:birth_weight, :class=>'input-large')
            %td= f.label(:abdominal)
            %td= f.text_field(:abdominal, :class=>'input-large')
          %tr
            %td= f.label(:birth_length, "Birt Length")
            %td= f.text_field(:birth_length, :class=>'input-large')
            %td= f.label(:obsterician)
            %td= f.text_field(:obsterician, :class=>'input-large')
          %tr
            %td.allergy{:colspan => "2"}
              %label Allergy
          %tr
            %td= f.label(:food, "1.Food")
            %td= f.text_field(:food, :class=>'input-large')
          %tr
            %td= f.label(:medicine, "2.Medicine")
            %td= f.text_field(:medicine, :class=>'input-large')
          %tr
            %td= f.label(:others, "3.Others")
            %td= f.text_field(:others, :class=>'input-large')

          / Feeding HIstory and Immunization  
          %tr 
            %th{:colspan => "2"}
              %h4 Feeding History and Immunization
          %tr
            %td= f.label(:type_of_feeding, "Type of Feeding")
            %td= f.text_field(:type_of_feeding, :class=>'input-xlarge')
          %tr
            %td= f.label(:supplementary)
            %td= f.text_field(:supplementary, :class=>'input-xlarge')
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/pediatrics/_list.html.haml
.records
  %h4.left
  = render(:partial => 'shared/search')
  %table.both.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %th Name
        %th Address
        %th Contact no.
        %th Actions
    - @pediatrics.each do |pedia|
      %tbody
        %tr{:class => cycle('odd', 'even')}
          %td= pedia.full_name
          %td= pedia.address
          %td= pedia.contact_no
          %td
            .btn-group
            - if current_user.admin? && !current_user?(pedia)
              = link_to raw('<i class="icon-tasks icons-black"></i>'), pedia_examinations_path(pediatric_id: pedia.id), role: "button", :class => 'btn', :title => 'examination'
              = link_to raw('<i class="icon-tag icons-black"></i>'), immunizations_path(pediatric_id: pedia.id), role: "button", :class => 'btn', :title => 'immunization'
              = link_to raw('<i class="icon-eye-open icons-black"></i>'), pedia, remote: true, role: "button", :class => 'btn', :title => 'view'
              = link_to raw('<i class="icon-pencil icons-black"></i>'), edit_pediatric_path(pedia), remote: true, role: "button", :class => 'btn', :title => 'edit'
              = link_to raw('<i class="icon-trash icons-black"></i>'), pedia, :confirm => 'Are you sure do you want to delete this record?', method: :delete, role: "button", remote: true, :class => 'btn', :title => 'delete'
            - else
              = link_to raw('<i class="icon-eye-open icons-black"></i>'), pedia, remote: true, role: "button", :class => 'btn', :title => 'view'

  .pagination
    = will_paginate(@pediatrics, :container => true)

app/views/pediatrics/_show.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
  %h3 Show Record
.modal-body
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th{:colspan=> '6'} Personal Information
    %tbody
      %tr
        %td Full Name: 
        %td{:colspan=> '5'}= @pediatric.full_name
      %tr
        %td Address: 
        %td{:colspan=> '5'}= @pediatric.address
      %tr
        %td Mother's Name: 
        %td= @pediatric.mother_name
        %td Occupation:
        %td= @pediatric.m_occupation
        %td Age: 
        %td= @pediatric.m_age
      %tr
        %td Fathers's Name: 
        %td= @pediatric.father_name
        %td Occupation:
        %td= @pediatric.f_occupation
        %td Age: 
        %td= @pediatric.f_age 
      %tr
        %td Birthdate: 
        %td{:colspan=> '5'}= @pediatric.birth_date
      %tr
        %td Age:
        %td{:colspan=> '5'}= @pediatric.f_age
      %tr
        %td Contact No: 
        %td{:colspan=> '5'}= @pediatric.contact_no

    %table.show-details.table.table-bordered
      %thead   
        %tr
          %th{:colspan => "4"} Birth History and Development
      %tbody    
        %tr
          %td Term:
          %td= @pediatric.term
          %td Head Circ
          %td= @pediatric.head_circ
        %tr
          %td Delivery
          %td= @pediatric.delivery
          %td Chest Circ
          %td= @pediatric.chest_circ
        %tr
          %td Birth Weight
          %td= @pediatric.birth_weight
          %td Abdominal
          %td= @pediatric.abdominal
        %tr
          %td Birth Length
          %td= @pediatric.birth_length
          %td Obstetrician
          %td= @pediatric.obsterician
        %tr
          %td.allergy{:colspan => "4"}
            %label Allergy
        %tr
          %td Food
          %td{:colspan => "3"}= @pediatric.food
        %tr
          %td Medicine
          %td{:colspan => "3"}= @pediatric.medicine 
        %tr
          %td Others
          %td{:colspan => "3"}= @pediatric.others
        %tr 
          %th{:colspan => "4"} Feeding History and Immunization
        %tr
          %td{:colspan => "3"} Type of Feeding
          %td Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        %tr
          %td{:colspan => "3"} Supplementary
          %td= @pediatric.supplementary
      
  %table.both.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %td{:colspan=> '5'} 
          %h4
            Immunization
    %tbody
      %tr
        %th Date
        %th Vaccine Name
        %th Vaccination Session
        %th Booster
        %th Vaccination Type
    - @immunizations.each do |immune|
      %tbody
        %tr{:class => cycle('odd', 'even')}
          %td= immune.created_at.strftime("%B %e, %Y")
          %td= immune.vaccination_name
          %td= immune.vaccination_session
          %td= immune.booster_session
          %td= immune.vaccination_type

  %table.show-details.table.table-bordered
    %thead
      %tr
        %th{:colspan=> '2'} Examination
    %tbody
      %tr
        %td Examination Date: 
        %td January 1, 2012
      %tr
        %td Weight:
        %td= @pediatric.weight
      %tr
        %td Height: 
        %td= @pediatric.height
      %tr
        %td History and Physical Examination:
        %td Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
      %tr
        %td Physician's Instructions
        %td Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
      %tr
        %td Created At:
        %td= @pediatric.created_at
      %tr
        %td Updated At:
        %td
.modal-footer
  = link_to raw('<i class="icon-print icons-black"></i>'), print_pedia_path(pediatric_id: @pediatric.id), id: 'my-link', title: 'print'
  %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/pediatrics/create.js.haml
- if @pediatric.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@pediatric))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show()
  $(":input:not(input[type=submit])").val("");
  $('#PediaAddRecord').modal('hide');
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/pediatrics/delete.html.erb
<% @page_title = "Delete Pedia Record" %>

	<div class="side-menu grid_5">
		<div class="side-menu-option">
			<%= render(:partial => 'pediatrics/sidenav') %>
		</div> <!-- end of side-menu-option -->
	</div> <!-- end of side-menu -->

	<div class="side-content grid_19">
		
		<div class="content-module">

			<div class="content-module-heading cf">
				<h3>DELETE PATIENT RECORD</h3>
			</div> <!-- end of side-content-heading -->
			
			<div class="content-module-main cf">
			
				<div class="sub-heading">
					<h4>Personal Information</h4>
				</div>
			<%= form_for(:pediatric, :url => {:action => 'destroy', :id => @pediatric.id}) do |f| %>
					<div class="personal-information-delete">	
			
						<p>
							<%= label(:full_name, "Full Name: ") %>
							<%= @pediatric.full_name %><br />
														
							<%= label(:birth_date, "Birth Date: ") %>
							<%= @pediatric.birth_date %><br />
															
							<%= label(:sex, "Sex: ") %>
							<%= @pediatric.sex %><br />
														
							<%= label(:age, "Age: ") %>
							<%= @pediatric.age %><br />
														
							<%= label(:address, "Address: ") %>
							<%= @pediatric.address %><br />
														
							<%= label(:contact_no, "Tel. no.: ") %>
							<%= @pediatric.contact_no %><br />
															
							<%= label(:mother_name, "Mother's Name: ") %>
							<%= @pediatric.mother_name %><br />
														
							<%= label(:m_occupation, "Mother's Occupation: ") %>
							<%= @pediatric.m_occupation %><br />
														
							<%= label(:m_age, "Mother's Age: ") %>
							<%= @pediatric.m_age %><br />
															
							<%= label(:father_name, "Father's Name: ") %>
							<%= @pediatric.father_name %><br />
							
							<%= label(:f_occupation, "Father's Occupation: ") %>
							<%= @pediatric.f_occupation %><br />
														
							<%= label(:f_age, "Father's Age: ") %>
							<%= @pediatric.f_age %><br />
						</p>
								
					</div>

					<%= submit_tag("DELETE", {:class => 'button round blue text-upper image-right ic-delete', :onclick=> "return confirm('Are you sure?')"}) %>
				</div> <!-- end of birthHistory-andDevelopment -->
		<% end -%>
		</div> <!-- end of content-module-main -->

	</div> <!-- end of content-module -->

</div> <!-- end of side-content -->

	

app/views/pediatrics/destroy.js.haml
$("#post_errors").hide(300);
$("#flash_notice").html("#{escape_javascript raw(flash_display)}");
$("#flash_notice").show()
$("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/pediatrics/index.html.haml
- @page_title = "List Pediatrics"
.container
  .header
    .left.subtitle
      %h1 Pedia
      %span
        %i.icon-list.icons-black
        List of Patient Records
    = link_to raw('<i class="icon-plus-sign icons-black"></i>&nbsp;&nbsp;Add Record'), "#PediaAddRecord", "role" => "button", "data-toggle" => "modal", :class => 'btn btn-success right'
  .content.both
    .row
      .span12
        #posts_list
          = render(:partial => "list")
          
#PediaAddRecord{'class' => 'modal hide fade record modal-pedia-add'}
  = render(:partial => "form")

#PediaEditRecord{'class' => 'modal hide fade record modal-pedia-add'}
  = render(:partial => "form")

#PediaShowRecord{'class' => 'modal hide fade modal-show modal-pedia-show'}
  = render(:partial => "show")

#PediaExamRecord{'class' => 'modal hide fade record'}
  = render(:partial => "examination")
  

app/views/pediatrics/list.html.erb
<% @page_title = "List Pediatrics" %>

	<div class="side-menu grid_5">
		<div class="side-menu-option">
			<%= render(:partial => 'pediatrics/sidenav') %>
		</div> <!-- end of side-menu-option -->
	</div> <!-- end of side-menu -->
	<div class="side-content grid_19">
		
		<div class="content-module">

			<div class="content-module-heading cf">
				<h3 class="grid_6">PEDIATRICS LIST OF RECORDS</h3>
				<%= render(:partial => 'shared/search') %>
			</div> <!-- end of side-content-heading -->
			
			<div class="content-module-main cf">
			
				<table class="patients-record">
					<thead>
						<tr>
							<th>id</th>
							<th>name</th>
							<th>address</th>
							<th>sex</th>
							<th>actions</th>
						</tr>
					</thead>
						<% @pediatrics.each do |pedia| %>
					<tbody>
						<tr class="<%= cycle('odd', 'even')%>">
							<td><%= pedia.id %></td>
							<td><%= pedia.full_name %></td>
							<td><%= pedia.address %></td>
							<td><%= pedia.sex %></td>
							<td>
								<%= link_to("", {:controller => 'immunizations', :action => 'list', :pediatric_id => pedia.id }, :class => 'table-immunization-button ic-table-immunization', :title => "immunization") %>
								<%= link_to("", {:action => 'show', :id => pedia.id }, :class => 'table-show-details ic-table-show', :title => "show") %>
								<%= link_to("", {:action => 'edit', :id => pedia.id }, :class => 'table-edit-button ic-table-edit', :title => "edit") %>
								<%= link_to("", {:action => 'delete', :id => pedia.id }, :class => 'table-delete-button ic-table-delete', :title => "delete") %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			<div class="pagination">
				<%= will_paginate(@pediatrics, :renderer => WillPaginate::ActionView::LinkRenderer) %>
			</div>
		</div> <!-- end of content-module-main -->
	</div> <!-- end of content-module -->
</div> <!-- end of side-content -->

app/views/pediatrics/print_records.html.haml
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th{:colspan=> '6'} Pediatrics Patient Information
  %tbody
    %tr
      %td Full Name: 
      %td{:colspan=> '5'}= @pedia.full_name
    %tr
      %td Address: 
      %td{:colspan=> '5'}= @pedia.address
    %tr
      %td Mother's Name: 
      %td= @pedia.mother_name
      %td Occupation:
      %td= @pedia.m_occupation
      %td Age: 
      %td= @pedia.m_age
    %tr
      %td Fathers's Name: 
      %td= @pedia.father_name
      %td Occupation:
      %td= @pedia.f_occupation
      %td Age: 
      %td= @pedia.f_age 
    %tr
      %td Birthdate: 
      %td{:colspan=> '5'}= @pedia.birth_date
    %tr
      %td Age:
      %td{:colspan=> '5'}= @pedia.f_age
    %tr
      %td Contact No: 
      %td{:colspan=> '5'}= @pedia.contact_no

  %table.show-details.table.table-bordered
    %thead   
      %tr
        %th{:colspan => "4"} Birth History and Development
    %tbody    
      %tr
        %td Term:
        %td= @pedia.term
        %td Head Circ
        %td= @pedia.head_circ
      %tr
        %td Delivery
        %td= @pedia.delivery
        %td Chest Circ
        %td= @pedia.chest_circ
      %tr
        %td Birth Weight
        %td= @pedia.birth_weight
        %td Abdominal
        %td= @pedia.abdominal
      %tr
        %td Birth Length
        %td= @pedia.birth_length
        %td Obstetrician
        %td= @pedia.obsterician
      %tr
        %td.allergy{:colspan => "4"}
          %label Allergy
      %tr
        %td Food
        %td{:colspan => "3"}= @pedia.food
      %tr
        %td Medicine
        %td{:colspan => "3"}= @pedia.medicine 
      %tr
        %td Others
        %td{:colspan => "3"}= @pedia.others
      %tr 
        %th{:colspan => "4"} Feeding History and Immunization
      %tr
        %td{:colspan => "3"} Type of Feeding
        %td Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      %tr
        %td{:colspan => "3"} Supplementary
        %td= @pedia.supplementary
%br
  %br
  %br
  %br 
  %br
  %br 
  %br
  %br 
  %br
  %br     
    %table.both.table.table-striped.table-hover.table-bordered
      %thead
        %tr
          %td{:colspan=> '5'} 
            %h4
              Immunization
      %tbody
        %tr
          %th Date
          %th Vaccine Name
          %th Vaccination Session
          %th Booster
          %th Vaccination Type
      - @immunizations.each do |immune|
        %tbody
          %tr{:class => cycle('odd', 'even')}
            %td= immune.created_at.strftime("%B %e, %Y")
            %td= immune.vaccination_name
            %td= immune.vaccination_session
            %td= immune.booster_session
            %td= immune.vaccination_type

    %table.show-details.table.table-bordered
      %thead
        %tr
          %th{:colspan=> '2'} Examination
      %tbody
        %tr
          %td Examination Date: 
          %td January 1, 2012
        %tr
          %td Weight:
          %td= @pedia.weight
        %tr
          %td Height: 
          %td= @pedia.height
        %tr
          %td History and Physical Examination:
          %td Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
        %tr
          %td Physician's Instructions
          %td Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
        %tr
          %td Created At:
          %td= @pedia.created_at
        %tr
          %td Updated At:
          %td

app/views/pediatrics/update.js.haml
- if @pediatric.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@pediatric))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show()
  $(":input:not(input[type=submit])").val("");
  $("#PediaEditRecord").modal("hide");
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");