config/routes.rb
OutpatientThesis::Application.routes.draw do

  resources :orthodontics
  resources :pediatrics
  resources :schedules
  resources :users
  resources :inventories
  resources :analytics
  resources :immunizations 
  resources :pendings
  resources :ortho_examinations
  resources :pedia_examinations
  resources :sessions
  
  match 'orthodontics', to: 'orthodontics#create'
  match '/home', to: 'access#home'
  match '/print_ortho', to: 'orthodontics#print_records'
  match '/print_pedia', to: 'pediatrics#print_records'
  match '/logout', to: 'sessions#destroy', via: :delete

  # T`he priority is based upon order of creation:
  # first created -> highest priority.
  # root :to => "public#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#login'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
  
end

app/models/pending.rb
class Pending < ActiveRecord::Base
    attr_accessible :full_name, :patient_status, :pending_for

    REGEX = /^([^\d\W]|[-\s])*$/

    validates :full_name, :presence => true, :format => { :with => REGEX }, :uniqueness => true, :length => {:maximum => 50}
    
  	def self.search(search, page)	
	paginate :per_page => 10, :page => page,
			 :conditions => ['full_name || lower(full_name) LIKE ?', "%#{search}%"],
			 :order => 'full_name'
	end

	# find pendings
	def self.pending_on
		Pending.where(:created_at => (Date.today))
	end
end

app/controllers/pendings_controller.rb
class PendingsController < ApplicationController

	layout 'admin'

	before_filter :confirm_logged_in
	before_filter :find_schedules
	before_filter :find_pendings
	before_filter :load

	def load
		@pendings = Pending.search(params[:search], params[:page])
		@pending = Pending.new
	end

	def index
		# @pendings = Pending.find(:all)
		# @date = params[:month] ? Date.parse(params[:month]) : Date.today
	end

	def show
		pending = Date.today
		@pendings = Pending.scheduled_on(pending)
		# if @pendings
		# flash[:notification] = 'Notification'
		# return true
		# else
		# return false
		# end
	end

	def create
		@pending = Pending.new(params[:pending])
		if @pending.save
			flash[:success] = 'Pending has been crated.'
		  @pendings = Pending.search(params[:search], params[:page])
		end
	end

	def edit
		@pending = Pending.find(params[:id])
	end

	def update
		@pending = Pending.find(params[:id])
		if @pending.update_attributes(params[:pending])
			flash[:success] = 'Pending has been updated.'
			@pendings = Pending.search(params[:search], params[:page])
		end
	end

	def destroy
		@pending = Pending.find(params[:id]).destroy
		flash[:success] = "Pending destroyed."
		@pendings = Pending.search(params[:search], params[:page])
	end

end

app/helpers/pendings_helper.rb
module PendingsHelper
end

app/views/pendings/_form.html.haml
= form_for @pending, remote: true  do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Pending
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@pending)
    .addrecord
      %table
        %tr
          %td= f.label(:full_name)
          %td= f.text_field(:full_name, :class=> 'round')
        %tr
          %td= f.label(:patient_status)
          %td= f.select(:patient_status, %w(HMO private))
        %tr
          %td= f.label(:pending_for)
          %td= f.select(:pending_for, %w(pediatric orthopedic))
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/pendings/_list.html.haml
.records
  %h4.left LIST OF PENDINGS
  = render(:partial => 'shared/search')
  %table.both.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %th name
        %th patient status
        %th pending for
        %th actions
    - @pendings.each do |pending|
      %tbody
        %tr{:class => cycle('odd', 'even')}
          %td= pending.full_name
          %td= pending.patient_status
          %td= pending.pending_for
          %td
            .btn-group
              = link_to raw('<i class="icon-pencil icons-black"></i>'), edit_pending_path(pending), remote: true, role: "button", :class => 'btn', :title => 'edit'
              = link_to raw('<i class="icon-trash icons-black"></i>'), pending, remote: true, :confirm => 'Are you sure?', method: :delete, role: "button", :class => 'btn', :title => 'delete'
  .pagination
    = will_paginate @pendings, :container => true

app/views/pendings/create.js.haml
- if @pending.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@pending))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show()
  $(":input:not(input[type=submit])").val("");
  $('#AddPending').modal('hide');
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/pendings/index.html.haml
- @page_title = "List of Pendings"
.contatiner
  .header
    .left.subtitle
      %h1 Pendings
      %span
        %i.icon-list.icons-black
        List of Pendings
    = link_to raw('<i class="icon-plus-sign icons-black"></i>&nbsp;&nbsp;Add Record'), "#AddPending", "role" => "button", "data-toggle" => "modal", :class => 'btn btn-success right'
  .content
    .row
      .span12
        #posts_list
          = render(:partial => "list")
#AddPending{'class' => 'modal hide fade record modal-ortho-add'}
  = render(:partial => "form")

#EditPending{'class' => 'modal hide fade record modal-ortho-add'}
  = render(:partial => "form")

app/views/pendings/list.html.erb
<% @page_title = "List of Pendings" %>

	<div class="side-menu grid_5">
		<div class="side-menu-option">
			<%= render(:partial => 'sidenav') %>
		</div> <!-- end of side-menu-option -->
	</div> <!-- end of side-menu -->
	<div class="side-content grid_19">
		<div class="content-module">
			<div class="content-module-heading cf">
				<h3 class="grid_6"> LIST OF PENDINGS </h3>

				<%= render(:partial => 'shared/search') %>

			</div> <!-- end of content-module-heading -->
			<div class="content-module-main">
				<table class="patients-record">
					<thead>
						<tr>
							<th>id</th>
							<th>name</th>
							<th>patient status</th>
							<th>pending for</th>
							<th>actions</th>
						</tr>
					</thead>
						<% @pendings.each do |pending| %>
					<tbody>
						<tr class="<%= cycle('odd', 'even')%>">
							<td><%= pending.id %></td>
							<td><%= pending.full_name %></td>
							<td><%= pending.patient_status %></td>
							<td><%= pending.pending_for %></td>
							<td>
								<%= link_to("", {:action => 'edit', :id => pending.id }, :class => 'table-edit-button ic-table-edit', :title => "edit") %>
								<%= link_to("", {:action => 'delete', :id => pending.id, :method => :destroy, confirm: "Are you sure?" }, :class => 'table-delete-button ic-table-delete', :title => "delete") %>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>	
					<div class="pagination">	
						<%= will_paginate @pendings, :container => false %>
					</div>
		</div> <!-- end of personal-information -->
				</div> <!-- end of content-module-main -->

			</div> <!-- end of content-module -->

	</div> <!-- end of page full width -->

app/views/pendings/update.js.haml
- if @pending.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@pending))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show()
  $(":input:not(input[type=submit])").val("");
  $("#EditPending").modal("hide");
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");