config/routes.rb
OutpatientThesis::Application.routes.draw do

  resources :orthodontics
  resources :pediatrics
  resources :schedules
  resources :users
  resources :inventories
  resources :analytics
  resources :immunizations 
  resources :pendings
  resources :ortho_examinations
  resources :pedia_examinations
  resources :sessions
  
  match 'orthodontics', to: 'orthodontics#create'
  match '/home', to: 'access#home'
  match '/print_ortho', to: 'orthodontics#print_records'
  match '/print_pedia', to: 'pediatrics#print_records'
  match '/logout', to: 'sessions#destroy', via: :delete

  # T`he priority is based upon order of creation:
  # first created -> highest priority.
  # root :to => "public#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#login'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
  
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	attr_accessible :name, :contact_no, :schedule_for, :scheduled_on, :time

	#has_and_belongs_to_many :editors, :class_name => "AdminUser"

	REGEX = /^([^\d\W]|[-\s])*$/

	# "sexy" validations
	validates :name, :presence => true, :length => {:maximum => 50}, :format => { :with => REGEX }
	validates :contact_no, :presence => true, :length => {:maximum => 15}
	validates :schedule_for, :presence => true
	validates :scheduled_on, :presence => true
	validates :time, :presence => true

	def self.search(search, page)	
	paginate :per_page => 10, :page => page,
			 :conditions => ['name || lower(name) LIKE ?', "%#{search}%"],
			 :order => 'name'
	end

	# find schedule_for
	def self.scheduled_on(schedules="")
		schedules = Schedule.find_by_scheduled_on(schedules)
		if schedules
		  return schedules
		else
		  return false
		end
	end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController

	layout 'admin'

	before_filter :confirm_logged_in
	before_filter :find_schedules
	before_filter :find_pendings
	before_filter :load

	def load
		@date = params[:month] ? Date.parse(params[:month]) : Date.today
		@schedules = Schedule.search(params[:search], params[:page])
		@schedule = Schedule.new
	end

	def index
	end

	def show
		@schedule = Schedule.find(params[:id])
		schedule = Date.today
		@schedules = Schedule.scheduled_on(schedule)
	end

	def create
		@schedule = Schedule.new(params[:schedule])
		if @schedule.save
		  flash[:success] = "Schedule has been created."
		  @schedules = Schedule.search(params[:search], params[:page])
		end
	end

	def edit
		@schedule = Schedule.find(params[:id])
	end

	def update
		@schedule = Schedule.find(params[:id])
		if @schedule.update_attributes(params[:schedule])
			flash[:success] = "Schedule has been updated."
			@schedules = Schedule.search(params[:search], params[:page])
		end
	end

	def destroy
		@schedule = Schedule.find(params[:id]).destroy
		flash[:success] = "Schedule destroyed."
		@schedules = Schedule.search(params[:search], params[:page])
	end

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_calendar.html.haml
%h2#month
  = link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-%d")
  = h @date.strftime("%B %Y")
  = link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-%d")
= calendar_for(@schedules, :year => @date.year, :month => @date.month) do |t|
  = t.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')
  - t.day(:day_method => :scheduled_on) do |date, schedules|
    = date.day
    - for schedule in schedules
      %li= link_to h(schedule.name), schedule, remote: true

app/views/schedules/_form.html.haml
= form_for @schedule, remote: true  do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Schedule
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@schedule)
    .addrecord
      %table
        %tr
          %td= f.label(:name)
          %td= f.text_field(:name, :class=> 'round')
        %tr
          %td= f.label(:contact_no, "Contact No.")
          %td= f.text_field(:contact_no, :class=> 'round')
        %tr
          %td= f.label(:schedule_for, "Schedule For")
          %td= f.select(:schedule_for, %w(pediatrics orthodontics))
        %tr
          %td= f.label(:scheduled_on)
          %td= f.text_field(:scheduled_on, :class=> 'input-medium datepicker', placeholder: 'YYYY-MM-DD')
        %tr
          %td= f.label(:time)
          %td= f.time_select(:time)
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/schedules/_list.html.haml
%h4.left
= render(:partial => 'shared/search')
%table.both.table.table-striped.table-hover.table-bordered
  %thead
    %tr
      %th Name
      %th Contact no.
      %th Schedule for
      %th Date
      %th Time
      %th Actions
  - @schedules.each do |sched|
    %tbody
      %tr{:class => cycle('odd', 'even')}
        %td= sched.name
        %td= sched.contact_no
        %td= sched.schedule_for
        %td= sched.scheduled_on.to_date.strftime("%B %e, %Y")
        %td= sched.time ? sched.time.strftime("%I:%M %p") : nil
        %td
          .btn-group
            = link_to raw('<i class="icon-pencil icons-black"></i>'), edit_schedule_path(sched), remote: true, role: "button", :class => 'btn', :title => 'edit'
            = link_to raw('<i class="icon-trash icons-black"></i>'), sched, remote: true, :confirm => 'Are you sure do you want to delete this record?', method: :delete, role: "button", :class => 'btn', :title => 'delete'
.pagination
  = will_paginate @schedules, :container => true

app/views/schedules/_show.html.haml
.modal-header
  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
  %h3 Outpatient Scheduled
.modal-body
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th{:colspan => "2"} Personal Information
    %tbody
      %tr
        %td Name
        %td= @schedule.name
      %tr
        %td Contact No.
        %td= @schedule.contact_no
      %tr
        %td Schedule For
        %td= @schedule.schedule_for
      %tr
        %td Scheduled On
        %td= @schedule.scheduled_on ? @schedule.scheduled_on.strftime("%B %e, %Y") : nil
      %tr
        %td Time
        %td= @schedule.time ? @schedule.time.strftime("%I:%M %p") : nil
.modal-footer
  %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/schedules/create.js.haml
- if @schedule.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@schedule))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show();
  $(":input:not(input[type=submit])").val("");
  $('#AddSched').modal('hide');
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");
  $("#calendar").html("#{escape_javascript( render(:partial => 'calendar'))}");

app/views/schedules/destroy.js.haml
$("#post_errors").hide(300);
$("#flash_notice").html("#{escape_javascript raw(flash_display)}");
$("#flash_notice").show();
$("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");
$("#sched_calendar").html("#{escape_javascript( render(:partial => 'calendar'))}");

app/views/schedules/index.html.haml
- @page_title = "List of Schedules"
.container
  .header
    .left.subtitle
      %h1 Schedule
      %span
        %i.icon-list.icons-black
        List of Schedules
    = link_to raw('<i class="icon-plus-sign icons-black"></i>&nbsp;&nbsp;Add Record'), "#AddSched", "role" => "button", "data-toggle" => "modal", :class => 'btn btn-success right'
  .content.both
    .row
      .span12
        .records
          .tabble
            %ul.nav.nav-tabs
              %li.active= link_to "Scheduled List", "#calendar_scheduled", "data-toggle" => "tab"
              %li= link_to "Scheduled Calendar", "#scheduled_list", "data-toggle" => "tab"
            .tab-content
              #calendar_scheduled{'class' => 'tab-pane active'}
                #posts_list
                  = render(:partial => "list")
              #scheduled_list{'class' => 'tab-pane tabbable-with-border'}
                #calendar
                  = render(:partial => "calendar")
                
#AddSched{'class' => 'modal hide fade record'}
  = render(:partial => "form")

#EditSched{'class' => 'modal hide fade record'}
  = render(:partial => "form")

#ShowSched{'class' => 'modal hide fade record'}
  = render(:partial => "show")

app/views/schedules/update.js.haml
- if @schedule.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@schedule))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show();
  $(":input:not(input[type=submit])").val("");
  $("#EditSched").modal("hide");
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");
  $("#sched_calendar").html("#{escape_javascript( render(:partial => 'calendar'))}");