config/routes.rb
OutpatientThesis::Application.routes.draw do

  resources :orthodontics
  resources :pediatrics
  resources :schedules
  resources :users
  resources :inventories
  resources :analytics
  resources :immunizations 
  resources :pendings
  resources :ortho_examinations
  resources :pedia_examinations
  resources :sessions
  
  match 'orthodontics', to: 'orthodontics#create'
  match '/home', to: 'access#home'
  match '/print_ortho', to: 'orthodontics#print_records'
  match '/print_pedia', to: 'pediatrics#print_records'
  match '/logout', to: 'sessions#destroy', via: :delete

  # T`he priority is based upon order of creation:
  # first created -> highest priority.
  # root :to => "public#index"
  # Sample of regular route:
  #   match 'products/:id' => 'catalog#view'
  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'sessions#login'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  match ':controller(/:action(/:id))(.:format)'
  
end

app/models/ortho_examination.rb
class OrthoExamination < ActiveRecord::Base
  attr_accessible :examination_date, :examination_result, :orthodontic_id
end

app/controllers/ortho_examinations_controller.rb
class OrthoExaminationsController < ApplicationController
  layout 'admin'

  before_filter :find_orthodontic
  before_filter :confirm_logged_in
  before_filter :load
  # before_filter :confirm_admin, :except => [:list, :new, :create, :add_new, :show]

  def load
    @ortho_exams = OrthoExamination.where(:orthodontic_id => @orthodontic.id)
    @ortho_exam = OrthoExamination.new(:orthodontic_id => @orthodontic.id)
  end

  def create
    @ortho_exams = OrthoExamination.new(params[:ortho_exam])
    if @ortho_exams.save
      flash[:success] = "Ortho Examination has been created."
      @ortho_exams = OrthoExamination.where(:orthodontic_id => @orthodontic.id)
    end
  end

  def edit
    @ortho_exam = OrthoExamination.find(params[:id])
  end
  
  def change
    @ortho_exams = OrthoExamination.find(params[:id])
    if @ortho_exams.update_attributes(params[:ortho_exam])
      flash[:success] = "Ortho Examination has been updated."
      @ortho_exams = OrthoExamination.where(:orthodontic_id => @orthodontic.id)
    end
  end

  def destroy
    @ortho_exams = OrthoExamination.find(params[:id]).destroy
    flash[:success] = "Ortho Examination destroyed."
    @ortho_exams = OrthoExamination.where(:orthodontic_id => @orthodontic.id)
  end

  private

  def find_orthodontic
    if params[:orthodontic_id]
      @orthodontic = Orthodontic.find_by_id(params[:orthodontic_id])
    end 
  end
end

app/helpers/ortho_examinations_helper.rb
module OrthoExaminationsHelper
end

app/views/ortho_examinations/_edit_form.html.haml
= form_for(:ortho_exam, :url => {:action => 'change', :id => @ortho_exam.id, :orthodontic_id => @orthodontic.id}, remote: true) do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Ortho Examination
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@ortho_exam)
    .addrecord
      %table
        %tr
          %td= f.label(:examination_date)
          %td= f.text_field(:examination_date, :class => 'input-medium datepicker', placeholder: 'YYYY-MM-DD', "data-date-format" => "yyyy-mm-dd")
        %tr
          %td= f.label(:examination_result)
          %td{:colspan => "8"}= f.text_area(:examination_result, :size => '40x5')
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/ortho_examinations/_form.html.haml
= form_for(:ortho_exam, :url => {:action => 'create', :orthodontic_id => @orthodontic.id}, remote: true) do |f|
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Ortho Examination
  .modal-body
    #post_errors.alert.alert-error{:style => "display:none"}
      - error_messages_for(@ortho_exam)
    .addrecord
      %table
        %tr
          %td= f.label(:orthodontic_id, "Ortho")
          %td= f.select(:orthodontic_id, [@orthodontic.id])
        %tr
          %td= f.label(:examination_date)
          %td= f.text_field(:examination_date, :class => 'input-medium datepicker', placeholder: 'YYYY-MM-DD', "data-date-format" => "yyyy-mm-dd")
        %tr
          %td= f.label(:examination_result)
          %td{:colspan => "8"}= f.text_area(:examination_result, :size => '40x5')
  .modal-footer
    = submit_tag("Submit", {:class => 'btn btn-primary'})

app/views/ortho_examinations/_list.html.haml
.records.clearfix
  %strong.left
    Name:
    = link_to @orthodontic.full_name, orthodontics_path 
  %br/
  %h4.left
  %table.both.table.table-striped.table-hover.table-bordered
    %thead
      %tr
        %th Examination Date
        %th Examination Result
        %th Actions
    - @ortho_exams.each do |exam|
      %tbody
        %tr{:class => cycle('odd', 'even')}
          %td= exam.examination_date.to_date.strftime("%B %e, %Y")
          %td= exam.examination_result
          %td
            .btn-group
              = link_to raw('<i class="icon-pencil icons-black"></i>'),  {:action => 'edit', :id => exam.id, :orthodontic_id => @orthodontic.id }, remote: true, role: "button", :class => 'btn', :title => 'edit'
              = link_to raw('<i class="icon-trash icons-black"></i>'), {:action => 'destroy', :id => exam.id, :orthodontic_id => @orthodontic.id }, role: "button", remote: true, method: :delete, :class => 'btn', :title => 'delete', :confirm => 'Are you sure do you want to delete this record?'

app/views/ortho_examinations/change.js.haml
- if @ortho_exam.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@ortho_exam))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show();
  $(":input:not(input[type=submit])").val("");
  $("#EditOrthoExam").modal("hide");
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/ortho_examinations/create.js.haml
- if @ortho_exam.errors.any?
  $("#flash_notice").hide(300);
  $("#post_errors").html("#{escape_javascript(error_messages_for(@ortho_exam))}");
  $("#post_errors").show(300);
- else
  $("#post_errors").hide(300);
  $("#flash_notice").html("#{escape_javascript raw(flash_display)}");
  $("#flash_notice").show()
  $(":input:not(input[type=submit])").val("");
  $('#AddOrthoExam').modal('hide');
  $("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/ortho_examinations/destroy.js.haml
$("#post_errors").hide(300);
$("#flash_notice").html("#{escape_javascript raw(flash_display)}");
$("#flash_notice").show();
$("#posts_list").html("#{escape_javascript( render(:partial => 'list'))}");

app/views/ortho_examinations/index.html.haml
- @page_title = "Ortho Examination List"
.container
  .header
    .left.subtitle
      %h1 Ortho Examination
      %span
        %i.icon-list.icons-black
        List of Ortho Examination Records
    = link_to raw('<i class="icon-plus-sign icons-black"></i>&nbsp;&nbsp;Add Record'), "#AddOrthoExam", "role" => "button", "data-toggle" => "modal", :class => 'btn btn-success right'
  .content.both
    .row
      .span12
        #posts_list
          = render(:partial => "list")
#AddOrthoExam{'class' => 'modal hide fade record modal-modal-exam'}
  = render(:partial => "form")

#EditOrthoExam{'class' => 'modal hide fade record modal-modal-exam'}
  = render(:partial => "edit_form")